services:
  # service configuration for our database
  database:

    # use the preferred version of the official Postgres image
    # see https://hub.docker.com/_/postgres/
    image: postgres:9.6.21
    environment:
      - POSTGRES_PASSWORD=Passw0rd!
    # persist the database between containers by storing it in a volume
    volumes:
      - db_data:/var/lib/postgresql/data

  # service configuration for our dockerized Rails app
  app:

    # use the Dockerfile next to this file
    build: .

    # rely on the RAILS_ENV value of the host machine
    # environment:
    #RAILS_ENV: $RAILS_ENV

    # makes the app container aware of the DB container
    depends_on:
      - database

    # expose the port we configured Unicorn to bind to
    ports:
      - "3000:3000"
    volumes: &app_volumes
      - ./config/secrets.yml:/var/www/consul/config/secrets.yml
      - storage:/var/www/consul/storage
    environment: &app_environment
      - POSTGRES_PASSWORD=Passw0rd!
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=enabled
  jobs:
    build: .
    depends_on:
      - database
      - app
    volumes: *app_volumes
    environment: *app_environment
    command: bundle exec rake jobs:work

volumes:
  db_data: {}
  storage: {}
